# Generated by Django 4.1.5 on 2023-02-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseold',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
