# Generated by Django 4.1.5 on 2023-02-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
